"""Schema 8 的独立 Living 表；迁移只建空表，不 enrollment。"""

LIVING_DDL = (
    """CREATE TABLE living_roots (
      root_id TEXT PRIMARY KEY NOT NULL, instance_id TEXT NOT NULL UNIQUE,
      owner_id TEXT NOT NULL, soul_id TEXT NOT NULL, world_id TEXT NOT NULL, timeline_id TEXT NOT NULL,
      generation TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision>=0),
      policy_revision INTEGER NOT NULL CHECK(policy_revision>=1), timezone_epoch INTEGER NOT NULL CHECK(timezone_epoch>=0),
      enabled INTEGER NOT NULL CHECK(enabled IN (0,1)), paused INTEGER NOT NULL CHECK(paused IN (0,1)),
      last_evaluated_at REAL, recovery_cursor TEXT, reconcile_until REAL, reconciliation INTEGER NOT NULL CHECK(reconciliation IN (0,1)),
      target TEXT NOT NULL, UNIQUE(owner_id,soul_id,world_id,timeline_id),
      FOREIGN KEY(world_id,owner_id) REFERENCES worlds(world_id,owner_id),
      FOREIGN KEY(world_id,timeline_id) REFERENCES world_timelines(world_id,timeline_id),
      FOREIGN KEY(soul_id,owner_id) REFERENCES souls(soul_id,owner_id))""",
    """CREATE TABLE living_policies (root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      revision INTEGER NOT NULL CHECK(revision>=1), payload TEXT NOT NULL, fingerprint TEXT NOT NULL,
      PRIMARY KEY(root_id,revision))""",
    """CREATE TABLE living_days (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      epoch INTEGER NOT NULL CHECK(epoch>=0), local_date TEXT NOT NULL, start REAL NOT NULL, end REAL NOT NULL CHECK(end>start),
      policy_revision INTEGER NOT NULL, revision INTEGER NOT NULL CHECK(revision>=1),
      state TEXT NOT NULL CHECK(state IN ('OPEN','CLOSED','PARTIAL')), updated REAL NOT NULL, visual TEXT NOT NULL,
      UNIQUE(root_id,epoch,local_date), UNIQUE(root_id,id),
      FOREIGN KEY(root_id,policy_revision) REFERENCES living_policies(root_id,revision))""",
    """CREATE TABLE living_locations (id TEXT NOT NULL, root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      revision INTEGER NOT NULL CHECK(revision>=1), category TEXT NOT NULL CHECK(category IN ('HOME','WORK','EXERCISE','CAFE','TRANSIT','SHOP','PARK','OTHER')),
      name TEXT NOT NULL, origin TEXT NOT NULL CHECK(origin='FICTIONAL_ROLE_STATE'), PRIMARY KEY(root_id,id,revision))""",
    """CREATE TABLE living_activities (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL, day_id TEXT NOT NULL,
      start REAL NOT NULL, end REAL NOT NULL CHECK(end>start), name TEXT NOT NULL,
      location_id TEXT NOT NULL, location_revision INTEGER NOT NULL, source TEXT NOT NULL,
      state TEXT NOT NULL CHECK(state IN ('PLANNED','ACTIVE','COMPLETED','SKIPPED','CANCELLED')),
      activated_at REAL, ended_at REAL, inferred INTEGER NOT NULL CHECK(inferred IN (0,1)), reason TEXT NOT NULL,
      UNIQUE(root_id,id), FOREIGN KEY(root_id,day_id) REFERENCES living_days(root_id,id),
      FOREIGN KEY(root_id,location_id,location_revision) REFERENCES living_locations(root_id,id,revision))""",
    "CREATE UNIQUE INDEX living_one_active_activity ON living_activities(root_id) WHERE state='ACTIVE'",
    """CREATE TABLE living_followups (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      due REAL NOT NULL, expires REAL NOT NULL CHECK(expires>due), topic TEXT NOT NULL, provenance TEXT NOT NULL,
      reason TEXT NOT NULL CHECK(reason IN ('REMEMBERED_FOLLOWUP','USER_PROMISED_FOLLOWUP')),
      state TEXT NOT NULL CHECK(state IN ('OPEN','RESOLVED','CANCELLED')), source_key TEXT NOT NULL,
      UNIQUE(root_id,source_key), UNIQUE(root_id,id))""",
    """CREATE TABLE living_observations (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      kind TEXT NOT NULL CHECK(kind IN ('WEATHER','HOLIDAY','SPECIAL_DATE')), provider TEXT NOT NULL, event_id TEXT NOT NULL,
      observed REAL NOT NULL, fetched REAL NOT NULL, expires REAL NOT NULL CHECK(expires>fetched AND fetched>=observed),
      payload TEXT NOT NULL, fingerprint TEXT NOT NULL, UNIQUE(root_id,provider,event_id), UNIQUE(root_id,id))""",
    """CREATE TABLE living_choices (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      event TEXT NOT NULL, purpose TEXT NOT NULL, algorithm TEXT NOT NULL, policy_revision INTEGER NOT NULL,
      input TEXT NOT NULL, input_fingerprint TEXT NOT NULL, value TEXT NOT NULL, fingerprint TEXT NOT NULL,
      UNIQUE(root_id,event,purpose,algorithm,policy_revision), UNIQUE(root_id,id),
      FOREIGN KEY(root_id,policy_revision) REFERENCES living_policies(root_id,revision))""",
    """CREATE TABLE living_opportunities (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL, day_id TEXT NOT NULL,
      kind TEXT NOT NULL CHECK(kind IN ('CONTACT','PHOTO','VOICE')), reason TEXT NOT NULL,
      source_type TEXT NOT NULL CHECK(source_type IN ('DAY','FOLLOWUP','ACTIVITY','OBSERVATION','CHOICE','LEGACY')),
      source_ref TEXT NOT NULL, occurrence TEXT NOT NULL, eligible REAL NOT NULL, expires REAL NOT NULL CHECK(expires>eligible),
      state TEXT NOT NULL CHECK(state IN ('OPEN','PLANNED','OFFERED','CONSUMED','EXPIRED','CANCELLED')),
      revision INTEGER NOT NULL CHECK(revision>=1), target TEXT NOT NULL, payload TEXT NOT NULL,
      UNIQUE(root_id,kind,source_ref,occurrence), UNIQUE(root_id,id),
      FOREIGN KEY(root_id,day_id) REFERENCES living_days(root_id,id))""",
    """CREATE TABLE living_schedule (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL REFERENCES living_roots(root_id),
      subject_type TEXT NOT NULL CHECK(subject_type IN ('DAY','ACTIVITY','OPPORTUNITY')), subject TEXT NOT NULL,
      occurrence TEXT NOT NULL, action TEXT NOT NULL CHECK(action IN ('CLOSE','ACTIVATE','COMPLETE','OFFER','EXPIRE')),
      priority INTEGER NOT NULL CHECK(priority BETWEEN 0 AND 3), due REAL NOT NULL, expires REAL NOT NULL CHECK(expires>=due),
      local_spec TEXT NOT NULL, policy_revision INTEGER NOT NULL, recovery_policy TEXT NOT NULL,
      state TEXT NOT NULL CHECK(state IN ('PENDING','CONSUMED','EXPIRED','CANCELLED')),
      UNIQUE(root_id,subject,occurrence,action), FOREIGN KEY(root_id,policy_revision) REFERENCES living_policies(root_id,revision))""",
    "CREATE INDEX living_schedule_due ON living_schedule(root_id,state,due,priority,id)",
    """CREATE TABLE living_decisions (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL, opportunity TEXT NOT NULL,
      input_version TEXT NOT NULL, policy_revision INTEGER NOT NULL, evaluated_at REAL NOT NULL,
      result TEXT NOT NULL CHECK(result IN ('ALLOW','SUPPRESS')), blockers TEXT NOT NULL, primary_blocker TEXT,
      next_check REAL, UNIQUE(opportunity,input_version,policy_revision), UNIQUE(root_id,id),
      FOREIGN KEY(root_id,opportunity) REFERENCES living_opportunities(root_id,id),
      FOREIGN KEY(root_id,policy_revision) REFERENCES living_policies(root_id,revision))""",
    """CREATE TABLE living_intents (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL, opportunity TEXT NOT NULL,
      decision_id TEXT NOT NULL UNIQUE, generation TEXT NOT NULL, reserved_at REAL NOT NULL, expires REAL NOT NULL CHECK(expires>reserved_at),
      state TEXT NOT NULL CHECK(state IN ('DECIDED','PREPARED','ATTEMPTED','CANCELLED','EXPIRED','QUARANTINED')),
      target TEXT NOT NULL, prepared TEXT, invalidated INTEGER NOT NULL CHECK(invalidated IN (0,1)),
      UNIQUE(root_id,id), FOREIGN KEY(root_id,opportunity) REFERENCES living_opportunities(root_id,id),
      FOREIGN KEY(root_id,decision_id) REFERENCES living_decisions(root_id,id))""",
    "CREATE UNIQUE INDEX living_one_live_intent ON living_intents(opportunity) WHERE state IN ('DECIDED','PREPARED','ATTEMPTED','QUARANTINED')",
    "CREATE INDEX living_budget ON living_intents(root_id,reserved_at)",
    """CREATE TABLE living_attempts (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL, intent TEXT NOT NULL UNIQUE,
      state TEXT NOT NULL CHECK(state IN ('CLAIMED','SENT','ACKNOWLEDGED','FAILED','UNKNOWN')),
      claimed_at REAL NOT NULL, runtime_id TEXT NOT NULL, target TEXT NOT NULL, request_fingerprint TEXT NOT NULL,
      message_id TEXT, sent_at REAL, UNIQUE(root_id,id), FOREIGN KEY(root_id,intent) REFERENCES living_intents(root_id,id))""",
    """CREATE TABLE living_delivery_results (id TEXT PRIMARY KEY NOT NULL, root_id TEXT NOT NULL, attempt TEXT NOT NULL,
      source TEXT NOT NULL, event_id TEXT NOT NULL, payload TEXT NOT NULL, fingerprint TEXT NOT NULL,
      UNIQUE(attempt,source,event_id), FOREIGN KEY(root_id,attempt) REFERENCES living_attempts(root_id,id))""",
    """CREATE TABLE living_inbound (root_id TEXT NOT NULL REFERENCES living_roots(root_id), source TEXT NOT NULL,
      event_id TEXT NOT NULL, received_at REAL NOT NULL, fingerprint TEXT NOT NULL, PRIMARY KEY(root_id,source,event_id))""",
    """CREATE TABLE living_operations (root_id TEXT NOT NULL REFERENCES living_roots(root_id), generation TEXT NOT NULL,
      producer TEXT NOT NULL, operation_id TEXT NOT NULL, payload TEXT NOT NULL, fingerprint TEXT NOT NULL,
      receipt TEXT NOT NULL, receipt_fingerprint TEXT NOT NULL, revision INTEGER NOT NULL,
      PRIMARY KEY(root_id,generation,producer,operation_id), UNIQUE(root_id,revision),
      FOREIGN KEY(root_id,revision) REFERENCES living_transitions(root_id,revision))""",
    """CREATE TABLE living_transitions (root_id TEXT NOT NULL REFERENCES living_roots(root_id), revision INTEGER NOT NULL CHECK(revision>=1),
      previous_revision INTEGER NOT NULL CHECK(previous_revision=revision-1), at REAL NOT NULL,
      action TEXT NOT NULL, changes TEXT NOT NULL, fingerprint TEXT NOT NULL, PRIMARY KEY(root_id,revision))""",
)


def create_living_schema(db):
    for sql in LIVING_DDL:
        db.execute(sql)
