"""Lore 仓储协议与固定失败码；业务算法不接触 SQLite。"""
from enum import Enum
from typing import Protocol


class LoreFailure(str, Enum):
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    AUTHORIZATION_DENIED = 'AUTHORIZATION_DENIED'
    NOT_AVAILABLE = 'NOT_AVAILABLE'
    SESSION_STALE = 'SESSION_STALE'
    BINDING_STALE = 'BINDING_STALE'
    REVISION_CONFLICT = 'REVISION_CONFLICT'
    IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT'
    VERSION_CONFLICT = 'VERSION_CONFLICT'
    BUDGET_INPUT = 'BUDGET_INPUT'
    STORAGE_BUSY = 'STORAGE_BUSY'
    STORAGE_CORRUPT = 'STORAGE_CORRUPT'
    SCHEMA_MISMATCH = 'SCHEMA_MISMATCH'
    RECOVERY_REQUIRED = 'RECOVERY_REQUIRED'
    PERSISTENCE_FAILURE = 'PERSISTENCE_FAILURE'


class LoreRuntimeError(RuntimeError):
    def __init__(self, code):
        self.code = code
        super().__init__(code.value)


def fail(code):
    raise LoreRuntimeError(code)


class LoreRepository(Protocol):
    """每个操作拥有独立连接与明确提交、回滚、关闭边界。"""

    def transaction(self, *, write=False): ...
    def close(self): ...


class LoreTransaction(Protocol):
    """领域层只见事务方法，不拼接或执行 SQL。"""

    world: object
    def revision(self, scope): ...
    def cas(self, scope, expected): ...
    def book(self, book_id): ...
    def version(self, book_id, version): ...
    def entries(self, book_id, version): ...
    def bindings(self, scope): ...
    def owner_books(self, owner_id): ...
    def replay(self, identity, producer, stamp): ...
    def audit(self, context, operation, book_id, version, identity, stamp, revision=None): ...
    def insert_book(self, book_id, owner_id, display_name, source_type, source_metadata, actor): ...
    def advance_version(self, book_id, owner_id, expected, next_version): ...
    def insert_version(self, book_id, version, proposal, stamp, actor): ...
    def insert_binding(self, scope, book_id, version, order, source): ...
    def delete_binding(self, scope, book_id): ...
    def set_enabled(self, scope, book_id, enabled): ...
    def set_version(self, scope, book_id, version): ...
    def scan_counts(self, book_id, version): ...
